name: Docs

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  runtime: ~/.local/share/nvim/site/pack/vendor/start
  nvim_url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate Docs
    steps:
      - name: Checkout with token
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Checkout without token
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Install neovim and dependencies
        run: |
          mkdir -p ${{ env.runtime }}
          mkdir -p _neovim
          curl -sL ${{ env.nvim_url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          ln -s $(pwd) ${{ env.runtime }}

      - name: Generate API docs
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          make api-docs

      - name: Generate plugin docs
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          make user-docs

      - name: Clean up
        run: |
          rm -rf _neovim/
          git status

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name != 'pull_request'
        with:
          commit_user_name: github-actions[bot]
          commit_message: "chore(docs): auto generate docs"
          branch: ${{ github.head_ref }}
