name: Tests

on:
  push:
    paths: [ 'lua/**', 'tests/**' ]
  pull_request:
    paths: [ 'lua/**', 'tests/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    name: Run tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        neovim_version: [ 'v0.10.4', 'v0.11.4', 'nightly']
        include:
        - os: macos-latest
          neovim_version: v0.11.4
        - os: windows-latest
          neovim_version: v0.11.4
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      # TODO: can be removed once we have fallback native search backend
      - name: Install ripgrep
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y ripgrep
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install ripgrep
          else
            choco install ripgrep -y
          fi
        shell: bash

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Run tests
        run: make test
